name: drengr
description: Drengr is a CLI and Framework for building expressive web servers in Dart.
version: 0.0.3
repository: https://www.github.com/pyrestudios/drengr

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
#  path: ^1.7.0
  path_to_regexp: ^0.4.0
  flat: ^0.4.0
  mustache_template: ^2.0.0
  yaml: ^3.1.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
