name: steward
description: Steward is a CLI and Framework for building expressive web servers in Dart.
version: 0.1.7
repository: https://www.github.com/pyrestudios/steward

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
#  path: ^1.7.0
  path_to_regexp: ^0.4.0
  flat: ^0.4.0
  mustache_template: ^2.0.0
  yaml: ^3.1.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  # These deps are used by the CLI
  recase: ^4.0.0
  bosun: ^0.2.0

