name: steward
description: Steward is a CLI and Framework for building expressive web servers in Dart.
version: 0.3.2
repository: https://www.github.com/pyrestudios/steward

environment:
  sdk: '>=2.17.0 <3.0.0'

executables:
  steward:

dependencies:
#  path: ^1.7.0
  path_to_regexp: ^0.4.0
  flat: ^0.4.0
  mustache_template: ^2.0.0
  yaml: ^3.1.0
  xml: ^6.4.2
  # These deps are used by the CLI
  recase: ^4.0.0
  bosun: ^0.2.2

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  mockito: ^5.1.0

